pg_local:
  host: 'localhost'
  name: 'postgres'
  user: 'postgres'
  password: 'postgres'
  port: 5432
stage:
  k8s: '/home/everhide/projects/do-tools/.secrets/k8s-stage.yaml'
  pull:
    exchange:
      host: 'postgresql-common-stage-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'rest_api'
      user: 'rest_api'
      password: 'ky06z616jdqg0tz7'
      port: 25060
    openapi:
      host: 'postgresql-openapi-stage-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'stage_open_api'
      user: 'open_api'
      password: 'gfmhh7w21x6mx19c'
      port: 25060
    landings:
      host: 'postgresql-landing-core-stage-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'stageland'
      user: 'stageland'
      password: 'hg1x8me3clff38he'
      port: 25060
prod:
  k8s: '/home/everhide/projects/do-tools/.secrets/k8s-prod.yaml'
  pull:
    exchange:
      host: 'postgresql-common-prod-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'rest_api_prod'
      user: 'rest_api_prod'
      password: 'jT1UbysOo1WHkGPZ'
      port: 25060
    openapi:
      host: 'postgresql-openapi-prod-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'openapi_prod'
      user: 'openapi_prod'
      password: 'JZ321a7SU9HLj9At'
      port: 25060
    landings:
      host: 'postgresql-landing-core-prod-fra1-do-user-8268209-0.b.db.ondigitalocean.com'
      name: 'landing_core_prod'
      user: 'landing_core'
      password: 'vURlMGvP9dlzuT6T'
      port: 25060
